services:
  reverseproxy:
    image: nginx:latest
    container_name: reverseproxy
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
     - "./nginx/SSL:/etc/nginx/certs:ro"
    depends_on:
     - threatdragon

  threatdragon:
    container_name: threatdragon
    image: owasp/threat-dragon:v2.5.0
    env_file: ./config.env
    expose:
     - "8080"
    volumes: 
      - "./config.env:/app/.env:ro"
